### ISSUE TITLE
Gardening and cartoon channel request - art text done 

### ISSUE THREAD

**Issue by hisameartwork** [miketweaver/DailyNews#14]
Hi! 

Thanks for making the news channel mod I, really enjoyed it. 
I do a lot of SDV gardening videos so people joked I should have my own TV channel, so here I am. I did the art and text for a gardening channel I just need code for it to work. I am not a programmer so I was hoping you could help me. 

**Do I have permission please, to use your code to make the two TV channels?**

I saw on nexus you are open to collaborations. If you don't have time to help me config no worries, I have spoken to someone who has offered to help me on the coding part so I can pester them with questions. To my understanding I would need the file thingy too, before it was compressed into a dll because that is where the days of the week are configured.  

Best regard,
Hisame

PS. I came here from the SDV discord group, they said to message you in the issue section. Not sure how anything works here so hope I sent the message in the right place. 
If you use FB or gmail we can talk faster there https://www.facebook.com/hisame.artworks/ :)

**Comment by miketweaver** [comment]
You can go ahead and use the code for what you would like, as long as you follow the License:

https://github.com/miketweaver/DailyNews/blob/master/LICENSE
